[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[build.environment]
  SUPABASE_URL = ""
  SUPABASE_SERVICE_KEY = ""
